Repository reqnroll/Reqnroll, pull requests merged in 2025-08, with the labels that each got.

#721 dotnet test - less verbose logging & no-restore
  .github/workflows/ci.yml
Labels: maintanance

#741 Make years in docs update "automatically"
  docs/conf.py
Labels: documentation

#738 Remove [Serializable] from exceptions, including serialisation constructors
  CHANGELOG.md
  Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/InvalidScenarioDependenciesException.cs
  Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/MissingScenarioDependenciesException.cs
  Plugins/Reqnroll.xUnit.ReqnrollPlugin/XUnitInconclusiveException.cs
  Plugins/Reqnroll.xUnit.ReqnrollPlugin/XUnitPendingStepException.cs
  Reqnroll.Generator/TestGeneratorException.cs
  Reqnroll/BoDi/ObjectContainerException.cs
  Reqnroll/ErrorHandling/AmbiguousBindingException.cs
  Reqnroll/ErrorHandling/BindingException.cs
  Reqnroll/ErrorHandling/ColumnCouldNotBeBoundException.cs
  Reqnroll/ErrorHandling/MissingStepDefinitionException.cs
  Reqnroll/ErrorHandling/ReqnrollException.cs
Labels: maintanance

#739 Dispose cancellationTokenSource in FormatterBase
  Reqnroll/Formatters/FormatterBase.cs
Labels: maintanance

#761 Allow Scenario, Feature and TestThreadContext to be resolved with their interfaces
  CHANGELOG.md
  Reqnroll/Infrastructure/ContextManager.cs
  Reqnroll/ReqnrollContext.cs
  Tests/Reqnroll.RuntimeTests/Infrastructure/ContextManagerTests.cs
  Tests/Reqnroll.RuntimeTests/Infrastructure/TestThreadContextTests.cs
Labels: enhancement

#766 Removed deprecated `<summary>` from NuGet packages
  CHANGELOG.md
  Plugins/Reqnroll.Assist.Dynamic/Reqnroll.Assist.Dynamic/Reqnroll.Assist.Dynamic.nuspec
  Plugins/Reqnroll.Autofac.ReqnrollPlugin/Reqnroll.Autofac.nuspec
  Plugins/Reqnroll.CustomPlugin/Reqnroll.CustomPlugin.nuspec
  Plugins/Reqnroll.ExternalData/Reqnroll.ExternalData.ReqnrollPlugin/Reqnroll.ExternalData.nuspec
  Plugins/Reqnroll.MSTest.Generator.ReqnrollPlugin/Reqnroll.MSTest.nuspec
  Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/Reqnroll.Microsoft.Extensions.DependencyInjection.nuspec
  Plugins/Reqnroll.NUnit.Generator.ReqnrollPlugin/Reqnroll.NUnit.nuspec
  Plugins/Reqnroll.SpecFlowCompatibility.Generator.ReqnrollPlugin/Reqnroll.SpecFlowCompatibility.nuspec
  Plugins/Reqnroll.TUnit.Generator.ReqnrollPlugin/Reqnroll.TUnit.nuspec
  Plugins/Reqnroll.Verify/Reqnroll.Verify.ReqnrollPlugin/Reqnroll.Verify.nuspec
  Plugins/Reqnroll.Windsor.ReqnrollPlugin/Reqnroll.Windsor.nuspec
  Plugins/Reqnroll.xUnit.Generator.ReqnrollPlugin/Reqnroll.xUnit.nuspec
  Reqnroll.Tools.MsBuild.Generation/Reqnroll.Tools.MsBuild.Generation.nuspec
Labels: documentation, maintanance

#771 Add an optional experimental feature that allows the VS extension to let the the discovered bindings written out to a file.
  Reqnroll/Bindings/Discovery/RuntimeBindingRegistryBuilder.cs
  Reqnroll/Bindings/Provider/BindingJsonSourceGenerator.cs
  Reqnroll/Bindings/Provider/BindingProviderService.cs
  Reqnroll/Infrastructure/DefaultDependencyProvider.cs
  Tests/Reqnroll.RuntimeTests/RuntimeBindingRegistryBuilderTests.cs
Labels: enhancement
